### ISSUE TITLE
Resource warning in test_ampute

### ISSUE THREAD

**Issue by RianneSchouten** [RianneSchouten/pyampute#12]
C:\Users\20200059\Documents\Github\pyampute\pyampute\utils.py:21: ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Users\\20200059\\Documents\\Github\\pyampute\\output.log' mode='a' encoding='cp1252'>
  logging.basicConfig(
ResourceWarning: Enable tracemalloc to get the object allocation traceback

**Comment by RianneSchouten** [comment]
Another one in test_inputs

C:\Users\20200059\Documents\Github\pyampute\pyampute\utils.py:21: ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Users\\20200059\\Documents\\Github\\pyampute\\output.log' mode='a' encoding='cp1252'>
  logging.basicConfig(
ResourceWarning: Enable tracemalloc to get the object allocation traceback

**Comment by prabhant** [comment]
Its because of not closing the file in python after opening it, its a pickle error

**Comment by davzaman** [comment]
What file is not being closed?  How is this error being produced / how are you running the test? Are you closing the test in the middle maybe?

**Comment by prabhant** [comment]
@davzaman you can find this warning here https://github.com/RianneSchouten/pyampute/runs/5100526595?check_suite_focus=true#step:5:9

**Comment by davzaman** [comment]
@prabhant Thank you! This is fixed with f90bf23
