### ISSUE TITLE
MCAR missingness does not give correct proportion

### ISSUE THREAD

**Issue by RianneSchouten** [RianneSchouten/pyampute#13]
In test_ampute, the following error occurs.

Traceback (most recent call last):
  File "C:\Users\20200059\Documents\Github\pyampute\pyampute\tests\test_ampute.py", line 56, in test_mechanisms
    self.assertAlmostEqual(
AssertionError: 1000 != 500.0 within 50.0 delta (500.0 difference)

As far as I can see, this happens with a MCAR mechanism. In that case, a warning occurs that says that all weighted sum scores are the same (which is true, they are all 0). The warning furthermore indicates that only in case of non-zero weighted sum scores, a MCAR mechanism will be applied.

I think we need to do three things:
1. The warning should not occur when someone asks for MCAR missingness, that is a bit confusing. Is that possible to implement?
2. We should apply a MCAR mechanisms when all weighted sum scores are 0. 
3. When they are all the same (as will happen with binary variables) they can theoretically also all be 0. In that case we would like the warning to occur (and still apply MCAR, as the warning currently indicates). We could check this by evaluating the mechanism (warning should only occur for MAR, MNAR, MAR+MNAR, or by evaluating the weights (at least one should be non-zero). Is that possible to implement?

**Comment by davzaman** [comment]
fixed with 4c55833
