### ISSUE TITLE
repeat patterns on the same variable

### ISSUE THREAD

**Issue by davzaman** [RianneSchouten/pyampute#17]
```python
        n = 1000
        X = np.random.randn(n, 2)
        patterns = [
            {"incomplete_vars": [0], "mechanism": "mcar"},
            {"incomplete_vars": [0], "mechanism": "mcar"},
        ]
        repeat_patterns = MultivariateAmputation(patterns=patterns)
        repeat_patterns.fit(X)
        # TODO: What to we expect the output to be?
```
What do we expect the behavior to be here? @RianneSchouten

**Comment by RianneSchouten** [comment]
I think we expect that candidates are divided over 2 patterns, where in each pattern `prop` rows are amputed. That means that the total number of incomplete rows equals prop. We could evaluate this with mdPatterns (where it may be good to have a test with a varying prop, and a test with an extra pattern. Something like this:
```
# test 1
n = 1000
X = np.random.randn(n, 2)
patterns = [
            {"incomplete_vars": [0], "mechanism": "mcar"},
            {"incomplete_vars": [0], "mechanism": "mcar"}
        ]
repeat_patterns = MultivariateAmputation(patterns=patterns, prop=0.3)
X_incompl = repeat_patterns.fit_transform(X)

mdp = mdPatterns()
patterns = mdp.get_patterns(X_incompl)

np.allclose(
                patterns.loc[1,"row_count"],
                (0.3 * n),
                atol=0.05 * n,
            )

# test 2
n = 1000
X = np.random.randn(n, 2)
patterns = [
            {"incomplete_vars": [0], "mechanism": "mcar", 'freq': 0.2},
            {"incomplete_vars": [0], "mechanism": "mcar", 'freq': 0.1},
            {"incomplete_vars": [1], "mechanism": "mar", 'freq': 0.7}
        ]
repeat_patterns = MultivariateAmputation(patterns=patterns)
X_incompl = repeat_patterns.fit_transform(X)

mdp = mdPatterns()
patterns = mdp.get_patterns(X_incompl)
np.allclose(
                patterns.loc[2,"row_count"],
                (0.2 * n * 0.5) + (0.1 * n * 0.5),
                atol=0.05 * n,
            )
```

If I run it now, it does not work properly.

**Comment by RianneSchouten** [comment]
@davzaman I am sorry for my incomplete message.

If you check the patterns, for the first test you will see that 50% of the rows get amputed instead of 30% of the rows.
In the second test, if you check the patterns, there are about 500 rows (5%) with missing values on variable 0, and it should be 1500 (15%).

The reason the tests were passing, is that I had only pasted code with np.allclose() without putting an assertTrue in front. I have adapted the test_ampute.py in b9d52a5 (and now it fails).

Can you try to resolve the issue in the amputation function?

**Comment by davzaman** [comment]
Oh dear I don't know how I missed the assert statement haha, I had checked it manually and it was looking ok but given I missed the assert who knows. I'll take a look today.
