### ISSUE TITLE
code coverage workflow error

### ISSUE THREAD

**Issue by davzaman** [RianneSchouten/pyampute#19]
@prabhant Thanks for writing the workflows! When I push I get this error on the code coverage workflow

```
[Error : .github#L1](https://github.com/RianneSchouten/pyampute/commit/ab9402bc55741579e615dd3e23ce1afeac88a3a5#annotation_2714764029)
the `uses' attribute must be a path, a Docker image, or owner/repo@ref
```

**Comment by prabhant** [comment]
I'm looking into this error now, looks like a problem with permissions. Will try to resolve it tomorrow
