### ISSUE TITLE
Warning in wrong places?

### ISSUE THREAD

**Issue by RianneSchouten** [RianneSchouten/pyampute#22]
I still feel we get a certain warning in places where it should not come.

[WARNING] Candidates for pattern 0 all have almost the same weighted sum scores. It is possible this is due to the use of binary variables in amputation. This creates problems when using the sigmoid function for the score_to_probability_func. Currently our solution is as follows: if there is just one candidate with a sum score 0, we will ampute it. If there is one candidate with a nonzero sum score, or multiple candidates with the same score, we evenly apply as if MCAR.

For instance, when I run test_ampute, I get warnings about similar weighted sum scores, but I do not feel that should be there. 
Do I overlook something?

**Comment by davzaman** [comment]
Should be fixed with f903e12, I was accidentally not checking for MCAR upon that warning. It should not trigger now when MCAR is the mechanism.
