### ISSUE TITLE
ENH: random number generation

### ISSUE THREAD

**Issue by tupui** [RianneSchouten/pyampute#30]
Great package 👏 

I have 2 suggestions 😃:

1. Use the new NumPy API to sample random numbers. Which is to say, use a `Generator` object: `rng = np.random.default_rng()` instead of using a global seed with `np.random.random()`. A lot of code in other libraries is not relying on this anymore and expect you to pass around a `Generator` object. More info [here](https://numpy.org/doc/stable/reference/random/index.html)
2. Look into using SciPy's QMC methods to do multivariate sampling. As the dimension grows, you will want to have a good sampling to prevent clustering and better follow the prescribed distributions (uniform or something else). More info [here](https://docs.scipy.org/doc/scipy/tutorial/stats.html#quasi-monte-carlo)

**Comment by davzaman** [comment]
Hi Pamphile! Great points, thanks for taking the time to look through our package. I'll look into this and get back to you

**Comment by davzaman** [comment]
Fixed with ad3172b
