### ISSUE TITLE
Are all warnings correct?

### ISSUE THREAD

**Issue by RianneSchouten** [RianneSchouten/pyampute#9]
When running the tests, there are some messages that say 'warn is deprecated, use logging.warn' instead.

**Comment by davzaman** [comment]
Can you specify which tests generate this message? I think I'm only ever calling `logging.warn`, so it could be a package being used is calling the deprecated function.

**Comment by RianneSchouten** [comment]
It occurs for test_ampute, here:

C:\Users\20200059\Documents\Github\pyampute\pyampute\ampute.py:354: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn(

**Comment by RianneSchouten** [comment]
And here in test_inputs

C:\Users\20200059\Documents\Github\pyampute\pyampute\ampute.py:334: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn(

**Comment by prabhant** [comment]
It just required to rename warn to warning, resolved here
e8f33ef337e682f6e706275adf78cd95890260cd

**Comment by davzaman** [comment]
also resolved 7494c1d
